# This jobs are only used for RSS service

####################################################################
# Refer to http://docs.shippable.com/reference/jobs-overview/      #
# Resources are located in shippable.resources.yml file            #
# Jobs are numbered to visualize sequence                          #
####################################################################

jobs:

  #1
  - name: rss-service_runCI
    type: runCI
    steps:
      - OUT: rss-service-master-docker-registry
      - OUT: rss-service-branch-docker-registry

  #2BRANCH
  - name: rss-service-manifest-branch
    type: manifest
    steps:
      - IN: rss-service-branch-docker-registry
      - IN: rss-service-docker-opts
      - TASK: managed
    flags:
      - rss-service

  #3BRANCH
  - name: rss-service-sit-deploy-branch
    type: deploy
    always:
      - NOTIFY: rss-slack-notifications
    steps:
      - IN: rss-service-manifest-branch # for non-master, don't auto deploy.
        switch: off
      - IN: rss-service-sit-ecs
      - IN: rss-service-sit-params
      - IN: rss-service-sit-alb-branch
        applyTo:
          - manifest: rss-service-manifest-branch
            image: rss-service-branch-docker-registry
            port: 3000
      - TASK: managed
        deployMethod: replace


  #2
  - name: rss-service-manifest-master
    type: manifest
    steps:
      - IN: rss-service-master-docker-registry
      - IN: rss-service-docker-opts
      - TASK: managed

  #3
  - name: rss-service-sit-deploy-master
    type: deploy
    always:
      - NOTIFY: rss-slack-notifications
    steps:
      - IN: rss-service-manifest-master # for master - auto deploy to SIT
        switch: on
      - IN: rss-service-sit-ecs
      - IN: rss-service-sit-params
      - IN: rss-service-sit-alb
        applyTo:
          - manifest: rss-service-manifest-master
            image: rss-service-master-docker-registry
            port: 3000
      - TASK: managed
        deployMethod: replace

  #4
  - name: rss-service-smoketest
    type: runSh
    always:
      - NOTIFY: rss-slack-notifications
    steps:
    - IN: rss-service-sit-deploy-master
    - IN: rss-service-repo
      switch: off
    - TASK:
      - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
      - script: source ~/.nvm/nvm.sh
      - script: nvm install "5.5.0"
      - script: nvm use "5.5.0"
      - script: cd ./IN/rss-service-repo/gitRepo/src
      - script: npm set registry http://npm.digital.bauer-media.net.au
      - script: npm install
      - script: URL=http://services.sit.bxm.internal/rss/ npm run test:smoke

  #5 PROD
  - name: rss-service-package-master
    type: release
    steps:
      - IN: rss-service-manifest-master
        switch: off
      - IN: rss-service-smoketest
      - IN: rss-service-version
      - TASK: managed
        bump: minor

  #6 PROD
  - name: rss-service-prod-deploy-master
    type: deploy
    always:
      - NOTIFY: rss-slack-notifications
    steps:
      - IN: rss-service-package-master
        switch: off
      - IN: rss-service-env-prod-ecs
      - IN: rss-service-prod-alb
      - IN: rss-service-alb-prod
        applyTo:
        - manifest: rss-service-manifest-master
          image: rss-service-master-docker-registry
          port: 3000
      - TASK: managed
        deployMethod: upgrade
