var chai = require('chai');
var sinon = require('sinon');
var sinonChai = require('sinon-chai');
chai.config.includeStack = true;
chai.use(sinonChai);
global.expect = chai.expect;
global.should = chai.should();
global.AssertionError = chai.AssertionError;
global.Assertion = chai.Assertion;
global.assert = chai.assert;
global.sinon = sinon;